### ISSUE TITLE
Asan leak detection from app_draw_classification

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#1502]
in my machine below error is periodically detected, although it seems it's not our fault.

<details>

```
30/31 app_draw_classification                FAIL            39.69s   exit status 1
>>> NNSTREAMER_FILTERS=/data/nntrainer/@simple/build/nnstreamer/tensor_filter MALLOC_PERTURB_=97 GTEST_OUTPUT=xml:/data/nntrainer/@simple/build/app_draw_classification.xml /data/nntrainer/@simple/build/Applications/TransferLearning/Draw_Classification/jni/nntrainer_training /data/nntrainer/@simple/build/res/app/Draw_Classification/Training.ini /data/nntrainer/@simple/build/res/app/Draw_Classification
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Listing only the last 100 lines from a long log.
#6/10 [          8           ]  ( Training Loss: 0.716475 )
#6/10 [          9           ]  ( Training Loss: 0.571569 )
#6/10 [          10          ]  ( Training Loss: 1.3373 )
#6/10 [          11          ]  ( Training Loss: 1.19535 )
#6/10 [          12          ]  ( Training Loss: 1.10272 )
#6/10 [          13          ]  ( Training Loss: 0.964459 )
#6/10 [          14          ]  ( Training Loss: 0.882366 )
#6/10 - Training Loss: 0.935067
#7/10 [          0           ]  ( Training Loss: 0.941786 )
#7/10 [          1           ]  ( Training Loss: 0.777751 )
#7/10 [          2           ]  ( Training Loss: 0.867707 )
#7/10 [          3           ]  ( Training Loss: 0.740157 )
#7/10 [          4           ]  ( Training Loss: 0.754959 )
#7/10 [          5           ]  ( Training Loss: 1.07918 )
#7/10 [          6           ]  ( Training Loss: 1.16289 )
#7/10 [          7           ]  ( Training Loss: 0.704269 )
#7/10 [          8           ]  ( Training Loss: 0.703262 )
#7/10 [          9           ]  ( Training Loss: 0.556836 )
#7/10 [          10          ]  ( Training Loss: 1.30184 )
#7/10 [          11          ]  ( Training Loss: 1.16781 )
#7/10 [          12          ]  ( Training Loss: 1.07242 )
#7/10 [          13          ]  ( Training Loss: 0.933386 )
#7/10 [          14          ]  ( Training Loss: 0.860016 )
#7/10 - Training Loss: 0.908284
#8/10 [          0           ]  ( Training Loss: 0.892923 )
#8/10 [          1           ]  ( Training Loss: 0.740625 )
#8/10 [          2           ]  ( Training Loss: 0.842667 )
#8/10 [          3           ]  ( Training Loss: 0.712269 )
#8/10 [          4           ]  ( Training Loss: 0.740726 )
#8/10 [          5           ]  ( Training Loss: 1.06457 )
#8/10 [          6           ]  ( Training Loss: 1.12722 )
#8/10 [          7           ]  ( Training Loss: 0.683186 )
#8/10 [          8           ]  ( Training Loss: 0.690319 )
#8/10 [          9           ]  ( Training Loss: 0.542751 )
#8/10 [          10          ]  ( Training Loss: 1.26763 )
#8/10 [          11          ]  ( Training Loss: 1.14166 )
#8/10 [          12          ]  ( Training Loss: 1.0431 )
#8/10 [          13          ]  ( Training Loss: 0.903932 )
#8/10 [          14          ]  ( Training Loss: 0.838932 )
#8/10 - Training Loss: 0.882167
#9/10 [          0           ]  ( Training Loss: 0.84572 )
#9/10 [          1           ]  ( Training Loss: 0.704674 )
#9/10 [          2           ]  ( Training Loss: 0.817497 )
#9/10 [          3           ]  ( Training Loss: 0.684889 )
#9/10 [          4           ]  ( Training Loss: 0.726038 )
#9/10 [          5           ]  ( Training Loss: 1.0499 )
#9/10 [          6           ]  ( Training Loss: 1.09115 )
#9/10 [          7           ]  ( Training Loss: 0.663399 )
#9/10 [          8           ]  ( Training Loss: 0.677781 )
#9/10 [          9           ]  ( Training Loss: 0.529373 )
#9/10 [          10          ]  ( Training Loss: 1.23445 )
#9/10 [          11          ]  ( Training Loss: 1.11671 )
#9/10 [          12          ]  ( Training Loss: 1.01458 )
#9/10 [          13          ]  ( Training Loss: 0.875969 )
#9/10 [          14          ]  ( Training Loss: 0.818948 )
#9/10 - Training Loss: 0.856738
#10/10 [          0           ]  ( Training Loss: 0.800231 )
#10/10 [          1           ]  ( Training Loss: 0.669885 )
#10/10 [          2           ]  ( Training Loss: 0.792256 )
#10/10 [          3           ]  ( Training Loss: 0.658051 )
#10/10 [          4           ]  ( Training Loss: 0.710992 )
#10/10 [          5           ]  ( Training Loss: 1.0352 )
#10/10 [          6           ]  ( Training Loss: 1.0549 )
#10/10 [          7           ]  ( Training Loss: 0.644922 )
#10/10 [          8           ]  ( Training Loss: 0.66566 )
#10/10 [          9           ]  ( Training Loss: 0.516654 )
#10/10 [          10          ]  ( Training Loss: 1.2022 )
#10/10 [          11          ]  ( Training Loss: 1.09288 )
#10/10 [          12          ]  ( Training Loss: 0.986797 )
#10/10 [          13          ]  ( Training Loss: 0.849455 )
#10/10 [          14          ]  ( Training Loss: 0.799993 )
#10/10 - Training Loss: 0.832005
Label for test file test1.bmp = could not be predicted with enough confidence.
Label for test file test2.bmp = could not be predicted with enough confidence.
Label for test file test3.bmp = could not be predicted with enough confidence.
Label for test file test4.bmp = could not be predicted with enough confidence.
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DrawClassification
[ RUN      ] DrawClassification.matchTestResult
[       OK ] DrawClassification.matchTestResult (0 ms)
[----------] 1 test from DrawClassification (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
stderr:

** (nntrainer_training:14677): CRITICAL **: 20:19:19.203: Failed to get EOS message

** (nntrainer_training:14677): CRITICAL **: 20:19:19.309: Failed to wait until state changed to PAUSED

=================================================================
==14677==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x7f4bfccad038 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10c038)
    #1 0x7f4bf9386bd8 in g_malloc (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51bd8)

SUMMARY: AddressSanitizer: 16384 byte(s) leaked in 1 allocation(s).
```

</details>

**Comment by kparichay** [comment]
This can be a bug from NNStreamerLayer as it does g_malloc, but it can be nnstreamer's internals as well.

**Comment by kparichay** [comment]
@zhoonit Is this still occuring?

**Comment by zhoonit** [comment]
It's occasionally happening, I'll update nnstreamer and check if problem persists

**Comment by zhoonit** [comment]
It's ubuntu 18.04, x86, i7-8700
