### ISSUE TITLE
Segmentation Fault with C++ API on Tizen

### ISSUE THREAD

**Issue by JRazek** [nnstreamer/nntrainer#1860]
Hello,
I am trying to run a simple program on a Tizen 6.5 platform with armv7l arch.
```cpp
#include <iostream>
#include <memory>

#include <nntrainer_cpp/model.h>

int main(int argc, char** argv) {
    using namespace ml::train;
    
    auto model=createModel(ModelType::NEURAL_NET);
    auto res=model->addLayer(layer::Input({"input_shape=1:1:10", "normalization=true"}));
    std::cout<<res<<'\n';
    return 0;   
}

```
The program crashes on the destructor of a model object. 
This only happens when the layer/optimizer is added to a model. 
A result of `model->addLayer()` is 0.
The gdb stacktrace I get:
```
Program received signal SIGSEGV, Segmentation fault.
0xb69fa69c in nntrainer::NeuralNetwork::~NeuralNetwork() () from target:/lib/libnntrainer.so
(gdb) bt
#0  0xb69fa69c in nntrainer::NeuralNetwork::~NeuralNetwork() () from target:/lib/libnntrainer.so
#1  0xb69fac28 in nntrainer::NeuralNetwork::~NeuralNetwork() () from target:/lib/libnntrainer.so
#2  0x00013788 in std::default_delete<ml::train::Model>::operator() (this=0xbefffc94, __ptr=0x44788) at /usr/arm-linux-gnueabi/include/c++/10/bits/unique_ptr.h:85
#3  0x00012e94 in std::unique_ptr<ml::train::Model, std::default_delete<ml::train::Model> >::~unique_ptr (this=0xbefffc94, __in_chrg=<optimized out>) at /usr/arm-linux-gnueabi/include/c++/10/bits/unique_ptr.h:361
#4  0x000124f4 in main (argc=1, argv=0xbefffe54) at /home/user/IoML/src/src/main.cpp:9
```
Program is being compiled with a following command 
```
arm-linux-gnueabi-g++  -I/home/user/IoML/src/include -I/home/user/IoML/deps/include -I/home/user/IoML/deps/include/nntrainer_cpp -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/network -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/nnstreamer -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/nntrainer -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/dlog -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/appfw -I/home/user/tizen-studio/platforms/tizen-6.5/wearable/rootstraps/wearable-6.5-device.core/usr/include/appcore-agent  -Ipch -g3 -Wall -O0 -fmessage-length=0 -march=armv7-a -fPIC -mfloat-abi=softfp -std=gnu++2a -o CMakeFiles/Main.dir/src/src/main.cpp.o -c /home/user/IoML/src/src/main.cpp
```
`arm-linux-gnueabi-g++ --version` returns 
`arm-linux-gnueabi-g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0`

I am using Tizen headed build from 17 March 2022, C++ API version `0.3.0-43.11`

**Comment by JRazek** [comment]
Ok, I managed to fix it. For some reason it complied successfully although the dependencies were not linked correctly.
